# Generated by Django 5.1 on 2024-09-26 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='File',
            new_name='file',
        ),
        migrations.AlterField(
            model_name='publication',
            name='image',
            field=models.FileField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='year',
            field=models.DateField(),
        ),
    ]
