# Generated by Django 5.1 on 2024-09-27 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_rename_file_publication_file_alter_publication_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='file',
            field=models.FileField(upload_to='uploads/files'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='image',
            field=models.FileField(upload_to='uploads/images/'),
        ),
    ]
