# Generated by Django 5.1 on 2024-09-27 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_alter_publication_file_alter_publication_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='file',
            field=models.FileField(upload_to='uploads/publications'),
        ),
    ]
