# Generated by Django 5.1 on 2024-10-04 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0004_alter_publication_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectinfo',
            name='scientific_case',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='summary',
            field=models.TextField(),
        ),
    ]
