# Generated by Django 5.1 on 2024-10-15 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0005_alter_projectinfo_scientific_case_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='source_id',
            new_name='source',
        ),
    ]
