# Generated by Django 5.1 on 2024-10-15 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0007_event_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='publications.event'),
        ),
    ]
