# Generated by Django 5.1 on 2024-10-15 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0008_alter_event_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.event')),
                ('project_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.projectinfo')),
            ],
        ),
    ]
